### ISSUE TITLE
Refactor into ES6 classes

### ISSUE THREAD

**Issue by jonhester** [tejasmanohar/node-schedule#125]
I think it would be great to refactor this into ES6. This would make it more future proof and separating concerns would make it a lot easier to maintain. Tying babel into test and prepublish generates the lib folder to run tests and when publishing. You can see the start of this [here](https://github.com/node-schedule/node-schedule/tree/es6). Tests are passing (except I forgot to update the lint script in the first commit), but it still needs more work and this would definitely be more than just a patch if and when this is merged.

Thoughts?

@tejasmanohar @santigimeno

**Comment by tejasmanohar** [comment]
That would make things a lot more organised and clean...

I think we should publish 1.0 with this (ES6) + refactors from #112 (job indexes, `getJobs()`) + #34 (timezone) (and maybe some other features, we'll see).

**Comment by jonhester** [comment]
Cool. I'll keep working on it and continue to keep it up to date with master. Still not linting properly on travis which is causing tests to fail. I'll get it sorted at soon, but probably not tonight.

**Comment by tejasmanohar** [comment]
Hey! Any progress on this, @jonhester? Just checking on progress, no actual deadlines this is open source :smile: ; also, what ES6 package are you using? I might jump in. Babel-node?

**Comment by jonhester** [comment]
Haven't done anything else yet. But might get some time this weekend. I already have it covered using babel. Just checkout the branch and npm install. Npm test will handle everything for you. Check the package.json scripts for more options.

**Comment by jonhester** [comment]
@tejasmanohar @santigimeno Wanted to let you know I haven't forgotten about this. I've been scarce on GitHub lately because I was moving abroad for my wife's job, and things changed up at the last minute to where we are just moving across the state. Too much information, but it has basically meant that the last month or so has been pretty rough time wise. Starting next week I'll have more time and will be more visible here again.

**Comment by tejasmanohar** [comment]
@jonhester No problem. Things have been really busy on my side as well in the last month. Hopefully, I'll get back to contributing more frequently in mid-May.

**Comment by jonhester** [comment]
New pull request sets up project for ES6. https://github.com/node-schedule/node-schedule/pull/152. Unfortunately, this is going to have to be manually merged since I'm changing so much. Tests and lint passes locally.

**Comment by jonhester** [comment]
@tejasmanohar @santigimeno , this pull request prepares for ES6 https://github.com/node-schedule/node-schedule/pull/153

**Comment by jonhester** [comment]
Once this gets merged into dev, I'll refactor schedule.js into ES6.

**Comment by tejasmanohar** [comment]
done :)
