### ISSUE TITLE
I did not know that every month (1,3,5,6) of the 5:19:40 to do the task of the time rules how to write, just a time rule can write it out?

### ISSUE THREAD

**Issue by Messilimeng** [tejasmanohar/node-schedule#158]
For example, number 4 in January, number 5, 9:30:30, to do one thing, just to make a rule, in January, 3 9:30:30, January 4 9:30:30, January, 5 9:30:30 to work.

**Comment by tejasmanohar** [comment]
Hey! I'm not sure exactly what you're saying. please ask in the gitter support chat
https://gitter.im/tejasmanohar/node-schedule?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by Messilimeng** [comment]
Can be write like this?

  var rule = new schedule.RecurrenceRule();
		rule.date = [3,4,6,7,8];
		rule.hour = 10;
		rule.minute = 11;
		rule.second = 30;
     var j = schedule.scheduleJob(date, function(){
       console.log('The world is going to end today.');
    });

**Comment by tejasmanohar** [comment]
Nope; And, I answered this in your last issue.

**Comment by tejasmanohar** [comment]
@Messilimeng see our `schedule.Range` feature :+1: 

```
var rule = new schedule.RecurrenceRule();
rule.dayOfWeek = [0, new schedule.Range(4, 6)];
rule.hour = 17;
rule.minute = 0;

var j = schedule.scheduleJob(rule, function(){
    console.log('Today is recognized by Rebecca Black!');
});
```

**Comment by Messilimeng** [comment]
If  have the rult.date  and  rult.month , write like rule.date = [0, new schedule.Range(8, 13)] or rult.month = [0, new schedule.Range(1, 8)]?

**Comment by tejasmanohar** [comment]
`rule.dayOfWeek`, not `.date`

@Messilimeng Really sorry but I just can't understand exactly what you mean. Both codes you posted do different things.
