### ISSUE TITLE
Incorrect cron format documentation

### ISSUE THREAD

**Issue by steven-** [tejasmanohar/node-schedule#161]
Hi,
The wiki says the [cron format](https://github.com/tejasmanohar/node-schedule/wiki/Cron-style-Scheduling) consists of: 
[MINUTE] [HOUR] [DAY OF MONTH] [MONTH OF YEAR] [DAY OF WEEK] [YEAR (optional)]

But it seems you are using [cron-parser](https://www.npmjs.com/package/cron-parser) so i guess the format actually is:
[SECOND] [MINUTE] [HOUR] [DAY OF MONTH] [MONTH OF YEAR] [DAY OF WEEK]

**Comment by jtwalters** [comment]
`[SECOND]` is optional, accordion to cron-parser. But, what about `[YEAR]`?

**Comment by steven-** [comment]
> [SECOND] is optional

Yes indeed.

> what about [YEAR]?

It does not seem to be supported. I checked, it's simply ignored.

**Comment by santigimeno** [comment]
@steven- @jtwalters 
Indeed, the wiki documentation is wrong. It should reflect the cron-parser format. I don't know if it's possible, but a PR to https://github.com/tejasmanohar/node-schedule.wiki.git to correct this would be great.

AFAIK there's not such thing as `year` in the `cron` format

**Comment by steven-** [comment]
> AFAIK there's not such thing as year in the cron format

There is in the so-called "enhanced" format.

>  a PR to correct this would be great.

Ok, I'm gonna do it.

**Comment by santigimeno** [comment]
@steven- never heard of it, but thanks for the heads up and thanks!

**Comment by steven-** [comment]
It seems I cannot do a PR for the wiki, you'll have to merge it manually if it's ok for you:
https://github.com/steven-/node-schedule.wiki.git

**Comment by santigimeno** [comment]
Ok, will try. Thanks!

**Comment by tejasmanohar** [comment]
@steven- i've enabled community edits on the wifi :smile:

**Comment by tejasmanohar** [comment]
your changes now are reflected here- https://github.com/tejasmanohar/node-schedule/wiki/Cron-style-Scheduling
