### ISSUE TITLE
how can I schedule a job every minute without using cron string?

### ISSUE THREAD

**Issue by lmessinger** [tejasmanohar/node-schedule#162]
Hi 

in cron string, "* * * * *" would schedule a job every minute.

can I do the same using a rule?

thanks very much
lior

**Comment by santigimeno** [comment]
@lmessinger Something like this should do it:

```
var schedule = require('node-schedule');

schedule.scheduleJob({second : 0}, function() {
	console.log(new Date());
});
```

**Comment by lmessinger** [comment]
thanks very much!

On Tue, Jun 16, 2015 at 3:27 PM, Santiago Gimeno <notifications@github.com>
wrote:

> @lmessinger <https://github.com/lmessinger> Something like this should do
> it:
>
> var schedule = require('node-schedule');
>
> schedule.scheduleJob({second : 0}, function() {
>     console.log(new Date());
> });
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tejasmanohar/node-schedule/issues/162#issuecomment-112407656>
> .
>



-- 
Lior Messinger
+1-646-3730044
+972-546-888401

**Comment by santigimeno** [comment]
np
