### ISSUE TITLE
Unable to call asynchronous functions repeatedly

### ISSUE THREAD

**Issue by gnoymmij** [tejasmanohar/node-schedule#163]
Hi, I'm trying to run some redis commands at some intervals
```code
var j = schedule.scheduleJob(rule, test(function(reply) {
  console.log(reply);
}));

function test(callback) {
  client.get('mykey', function (err, reply) {
    callback(reply);
  });
}
```
However, it executes successfully once and then subsequently execution resulted in error:
```
Cannot read property 'execute' of undefined
```

What am I doing wrong? Please advise.

**Comment by santigimeno** [comment]
@gnoymmij The second parameter of the `scheduleJob` function should be a function. Try with this instead:
```
var j = schedule.scheduleJob({ second: 0 }, function() {
    test(function(reply) {
        console.log(reply);
    }); 
});
```

**Comment by gnoymmij** [comment]
@santigimeno Nothing happens when I do it this way... I verified this by trying to delete a key rather than getting a key from redis.

**Comment by santigimeno** [comment]
@gnoymmij Take into account that I'm scheduling the job to be executed every minute (every time the second = 0)
For example this test is working correctly for me and writes `hello` every minute.
```
var j = schedule.scheduleJob({ second: 0 }, function() {
	test(function(reply) {
		console.log(reply);
	});
});

function test(cb) {
	setTimeout(function() {
		cb('hello');
    }, 100);
}
```

**Comment by gnoymmij** [comment]
@santigimeno I tried your example and it works. But when I change the test function to:
```
function test(cb) {
  client.get('mykey', function(err, reply) {
    console.log('did this print?');
    cb(reply);
  }
}
```
Nothing seems to be executing, not even the console.log statement within the test function...

**Comment by santigimeno** [comment]
@gnoymmij It looks like a problem inside your function, not in `node-schedule`

**Comment by gnoymmij** [comment]
@santigimeno I managed to make it work. I had to move the redis commands out to another file and export the function as a module.

Thanks for the help.

**Comment by hydrix9** [comment]
I get this error

`Cannot read property 'execute' of undefined`

when I try to run

`schedule.scheduleJob('*/5 * * * * *', UpdateTiles("5sec"));`

as opposed to

```
schedule.scheduleJob('*/5 * * * * *', Update5Sec);
function Update5Sec() {
UpdateTiles("5sec");
}
```

which works perfectly

**Comment by mKontakis** [comment]
@hydrix9 Did you manage to fix it?
