### ISSUE TITLE
Cron scheduler does not run as expected

### ISSUE THREAD

**Issue by shamsher31** [tejasmanohar/node-schedule#166]
We have set the cron scheduler as per the following.<br>
45 23 * * 1-6 * <br>

Which is as per the following blog http://www.thegeekstuff.com/2009/06/15-practical-crontab-examples/ <br>

Run the Scheduler from Mon to Sat at 11:45 PM.

But it does not work as expected<br>

Even when we write "45 02 * * * *", it means scheduler should run at 02:45 AM. But its running every hour.

**Comment by santigimeno** [comment]
Hi @shamsher31,
Regarding your first example, and looking and the format we're supporting: https://github.com/harrisiirak/cron-parser, it should run every hour at minute 45 and second 23 from January to June.
The second example should run every hour at minute 02 and second 45.
Notice that if you're using a cron format with 6 values, the first value configures the second the job is to be executed.

**Comment by shamsher31** [comment]
Thanks @santigimeno for your quick response. So if I use cron format with 5 values, it will be consider mins, hours and so on.
