### ISSUE TITLE
Offset scheduling?

### ISSUE THREAD

**Issue by zettam** [tejasmanohar/node-schedule#170]
I couldn't no find a way to make cron-style offsets work. example:

'0 */10+5 * * * *'

> expected: run every 10 minutes + 5 minutes
5, 15, 25, 35, 45, 55

**Comment by santigimeno** [comment]
@zettam If it's not supported by https://github.com/harrisiirak/cron-parser, it's not supported by `node-schedule`.

You could always implement it with multiple jobs

**Comment by tejasmanohar** [comment]
Right

**Comment by gautamverma** [comment]
Can anyone provide a example how to do this using multiple jobs.

**Comment by santigimeno** [comment]
```
var schedule = require('node-schedule');
var clock = require('sinon').useFakeTimers();

function your_job() {
	console.log(new Date());
    console.log('This is my job');
}

var j1 = schedule.scheduleJob({ minute : 5 }, your_job);
var j2 = schedule.scheduleJob({ minute : 15 }, your_job);
var j3 = schedule.scheduleJob({ minute : 25 }, your_job);
var j4 = schedule.scheduleJob({ minute : 35 }, your_job);
var j5 = schedule.scheduleJob({ minute : 45 }, your_job);
var j6 = schedule.scheduleJob({ minute : 55 }, your_job);

clock.tick(10 * 60 * 60 * 1000);

```

**Comment by tejasmanohar** [comment]
@santigimeno has provided a sample implementation so I'm going to close this until further commenting :smile:
