### ISSUE TITLE
Job.prototype.schedule doesn't add job into scheduledJob

### ISSUE THREAD

**Issue by spinosae** [tejasmanohar/node-schedule#173]
Job wasn't added to scheduledJob object when being scheduled with job.schedule. Is there a reason for this behavior? Or you missed this out?

**Comment by santigimeno** [comment]
@spinosae Probably we missed it. Let me think a little about it. Thanks for the report!

**Comment by tejasmanohar** [comment]
oh, it is something we missed here- https://github.com/tejasmanohar/node-schedule/blob/master/lib/schedule.js#L139

only jobs scheduled via `scheduleJob()` are being added right now, oops

**Comment by santigimeno** [comment]
Fix already landed https://github.com/tejasmanohar/node-schedule/commit/1e7e09bfd8cf3a1538be803e10f29e795603602c
