### ISSUE TITLE
Sample code does not works

### ISSUE THREAD

**Issue by VikramTiwari** [tejasmanohar/node-schedule#174]
I tried the very basic code, with a little changes, and it does not works.

```
var schedule = require('node-schedule');

schedule.scheduleJob('1 * * * * *', function() {
	console.log('The answer to life, the universe, and everything!');
});

```

**Comment by santigimeno** [comment]
@VikramTiwari It works for me: the job is triggered every minute on second 1. What is the behaviour you would expect?

**Comment by VikramTiwari** [comment]
Ah! My assumption was wrong. I was expecting it to run every second. :+1: Sorry. Closing this. :)

**Comment by tejasmanohar** [comment]
Side note- If you want something to run every second, you're probably better off using setInterval instead of node schedule
