### ISSUE TITLE
Scheduler does not execute job when provided with UTC Date information.

### ISSUE THREAD

**Issue by 0nix** [tejasmanohar/node-schedule#178]
I have the need of executing a job at certain times, and I use UTC Dates to keep track of them. I push jobs on the scheduler using the following code:
`setScheduledChange(timestamp + (timelimit * 1000));	
function setScheduledChange(date{
	schedule.scheduleJob(date,function(){
		//something happens here
	});
}
`
This means I'm executing the job at `timestamp` + `timelimit` seconds. Because in your wiki you schedule Date using the Date constructor, I assumed the scheduler alots time according to the UTC Date. This does not happen. Am I doing something wrong?

**Comment by santigimeno** [comment]
I'm not sure UTC dates (milliseconds I assume) are supported. @tejasmanohar ?
Adding support for them shoudn't be that hard.

**Comment by tejasmanohar** [comment]
Very easy. I'll take care of this :)

**Comment by santigimeno** [comment]
@tejasmanohar don't worry. See https://github.com/tejasmanohar/node-schedule/pull/181

**Comment by santigimeno** [comment]
Functionality added in commit https://github.com/tejasmanohar/node-schedule/commit/14a1d915faf04917cced3108e490c030210c8d85
