### ISSUE TITLE
Schedule only works the first hour

### ISSUE THREAD

**Issue by vnistor** [tejasmanohar/node-schedule#185]
I'm scheduling to run a function at the preset minutes of every hour. But it only runs the function at the preset minutes the first hour, and then stops. I'm working off the two examples in the wiki. Am I missing something?
```
var schedule = require('node-schedule');
var rule = new schedule.RecurrenceRule();
rule.minute = [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55];

var j = schedule.scheduleJob(rule, function () {
    settle.local (function (err, res) {
      if (err) {
          return console.log(err);
      } else {
          return console.log(res);
      }
    });
});
```
It works just fine the first hour, but the function is not executed in any subsequent hours.

**Comment by santigimeno** [comment]
It's working for me:
```
var schedule = require('node-schedule');
var clock = require('sinon').useFakeTimers();
var assert = require('assert');

var rule = new schedule.RecurrenceRule();
rule.minute = [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55];

var i = 0;
var j = schedule.scheduleJob(rule, function () {
    console.log('hello' + ++i);
});

/* Advance 3 hours*/
clock.tick(10800 * 1000);
assert.equal(i, 12 * 3);
```

**Comment by vnistor** [comment]
I see it does. However, for my code, the console says:

[Schedule] 2015-09-01T18:20:00.296Z         No unsettled transactions
[FX] 2015-09-01T18:20:36.108Z               BT EURRON @ 4.3875 / 4.4875
[Schedule] 2015-09-01T18:25:00.288Z         No unsettled transactions
[FX] 2015-09-01T18:25:36.026Z               BT EURRON @ 4.3875 / 4.4875
[Schedule] 2015-09-01T18:30:00.287Z         No unsettled transactions
[FX] 2015-09-01T18:30:36.084Z               BT EURRON @ 4.3875 / 4.4875
[Schedule] 2015-09-01T18:35:00.288Z         No unsettled transactions
[FX] 2015-09-01T18:35:36.125Z               BT EURRON @ 4.3875 / 4.4875
[Schedule] 2015-09-01T18:40:00.286Z         No unsettled transactions
[FX] 2015-09-01T18:40:36.062Z               BT EURRON @ 4.3875 / 4.4875
[Schedule] 2015-09-01T18:45:00.290Z         No unsettled transactions
[FX] 2015-09-01T18:45:36.056Z               BT EURRON @ 4.3875 / 4.4875
[Schedule] 2015-09-01T18:50:00.286Z         No unsettled transactions
[FX] 2015-09-01T18:50:36.056Z               BT EURRON @ 4.3875 / 4.4875
[Schedule] 2015-09-01T18:55:00.288Z         No unsettled transactions
[FX] 2015-09-01T18:55:36.115Z               BT EURRON @ 4.3875 / 4.4875
[Schedule] 2015-09-01T19:00:00.284Z         No unsettled transactions
[FX] 2015-09-01T19:00:36.052Z               BT EURRON @ 4.3875 / 4.4875
[FX] 2015-09-01T19:05:36.104Z               BT EURRON @ 4.3875 / 4.4875
[FX] 2015-09-01T19:10:36.128Z               BT EURRON @ 4.3875 / 4.4875
[FX] 2015-09-01T19:15:36.138Z               BT EURRON @ 4.3875 / 4.4875
[FX] 2015-09-01T19:20:36.074Z               BT EURRON @ 4.3875 / 4.4875

[FX] runs on a 5 minute setInterval.
[Schedule] just stops after it hits 0 again.

**Comment by vnistor** [comment]
So basically you're saying that the logic I am using with setting up the rule is correct.

**Comment by vnistor** [comment]
It seems to be working after switching to:
rule.minute = new schedule.Range(0, 59, 5);

Not sure why it was stopping before. Looked like it was only going over the array once.

**Comment by santigimeno** [comment]
@vnistor I don't really know. Can you come up with a reduced case I can execute that reproduces the problem? Thanks!

**Comment by tejasmanohar** [comment]
Closing this due to lack of response from @vnistor
