### ISSUE TITLE
How to access a Job instance from different files of an application?

### ISSUE THREAD

**Issue by scaryguy** [tejasmanohar/node-schedule#186]
Hey @tejasmanohar, how to you share a job instance inside a single instance while Job is created in a separate `.js` file and if you wan't to access it from another `.js` file?

Let's say I have a job created inside `lib/one.js` file:

```js
var cue_out_scheduler = scheduler(date, function cue_out_scheduler() { .... }
```

And I want to cancel this specific `cue_out_scheduler` file inside `lib/two.js` file.

```js
cue_out_scheduler.cancel();
```

How to do that?

**Comment by tejasmanohar** [comment]
Hey @scaryguy! So, this is rather simple to accomplish.

You can make a module in `lib/one.js` that exports a function executing the `cancel()` function on your job created through node-schedule.

**Comment by tejasmanohar** [comment]
one.js ->
```
import schedule from 'node-schedule'

let d = new Date()
d.setSeconds(d.getSeconds() + X)

let s = schedule.scheduleJob(d, () => console.log('done'))

export function cancel() {
  console.log('cancelled')
  s.cancel();
}
```

two.js ->
```
import { cancel } from './one'

setTimeout(cancel, Y);
```

here's a really quick (kinda sloppy) example i put together. you can play around with these values to see that it works.

i.e. try putting in X as `5` and Y as `4`... or switch it. the cancel function mutates the schedule object in the first module. sorry that the example code is in ES6.... very similar in ES5 with `module.exports` - see http://www.sitepoint.com/understanding-module-exports-exports-node-js/

**Comment by tejasmanohar** [comment]
i.e.

```
exports.cancel = function() {
  s.cancel();
};
```

also, use function() { } instead of =>, read here for the difference- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

**Comment by scaryguy** [comment]
I'm gonna try it! Thanks in advence! If I'm unable to implement I may disturb you again, if you don't mind :)

**Comment by tejasmanohar** [comment]
No problem! Modules are very useful- you should explore them more :smile:

**Comment by scaryguy** [comment]
I've just managed it to work with your help Tesaj, thank you very much! :wink:

**Comment by tejasmanohar** [comment]
No problem
