### ISSUE TITLE
Cannot find module 'node-schedule'

### ISSUE THREAD

**Issue by lijuicsoft** [tejasmanohar/node-schedule#187]
My Node version is 0.12.7 and npm version is 2.11.3. I am using windows 7-  64 bit
I installed  'node-schedule' using *npm install node-schedule* .

i try to access node in my js code , in localhost 
*var schedule = require('node-schedule');* 
that time its show error : Cannot find module 'node-schedule'

how to solve this problem.

thanks in advance

**Comment by tejasmanohar** [comment]
Odd. Sounds like somethings' wrong with your node configuration- other modules work? Going to be *very tough* to debug this; would you post a link to a git repo w/ node_modules/.

Also try to rebuild / re-install all modules w/ npm.

**Comment by tejasmanohar** [comment]
Closed due to inactivity. Is this still an issue?

**Comment by lijuicsoft** [comment]
i upgraded win 7 to 10 , same problem is existing .

Currently i copied ,"node_schedule"  folder in local server folder  and using

*var schedule = require('./node-schedule/lib/schedule.js')*; instead of *var schedule = require('node-schedule')*;

**Comment by tejasmanohar** [comment]
require'ing should look at node_modules for your path in a normal node app.

do any other modules in node_modules/ folder work for you? @lijuicsoft

**Comment by lijuicsoft** [comment]
net , http  etc modules are working properly

**Comment by tejasmanohar** [comment]
@lijuicsoft modules that you've installed via npm, not system modules that you've required.

**Comment by lijuicsoft** [comment]
i installed *npm install grunt * , this module is also not working

**Comment by tejasmanohar** [comment]
@lijuicsoft Then, it's a configuration issue on your end and not a bug in node-schedule. I'd start w/ installing Node from scratch based on official guides in the wiki... but I'm not 100% sure since I can't play around with your installation.

**Comment by lijuicsoft** [comment]
i hope that ll help me, thank you for reply @tejasmanohar
