### ISSUE TITLE
Recurrence on last day of month?

### ISSUE THREAD

**Issue by aktary** [tejasmanohar/node-schedule#188]
I can't really tell from the examples how one would schedule a recurring job to execute on the last day of the month... keeping in mind that months have variable lengths.  How would I do this?

**Comment by aktary** [comment]
Never mind.  I just saw this on [Unsupported Features] (https://github.com/tejasmanohar/node-schedule/wiki/Cron-style-Scheduling#unsupported-cron-features):

>Currently, W (nearest weekday), L (last day of month/week), and # (nth weekday of the month) are not supported.

**Comment by msageryd** [comment]
A little late to the party, but I'll leave some code here if someone else ends up here looking for a last-in-month solution.

```
schedule.scheduleJob(rule, function(current) {
  const next = this.nextInvocation();

  if (next.getMonth() !== current.getMonth()) {
    //Do your last-in-month-stuff
  }
});
```

N.B. You cannot use a fat-arrow function here since you'll end up with the wrong `this` if you do.
